# action.yml
name: 'Render Rmd site'
description: 'Render Rmd site under data and vignettes'
inputs:
  render-site:
    description: Should it render site?
    required: true
    default: true
  webhook:
    description: discord webhook to be used in R
    required: true
    default: ""
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.render-site }}
    - ${{ inputs.webhook }}
