on:
  push:
  schedule:
    - cron: '12 7 * * 1/3'

jobs: 
  build_docker:
    runs-on: ubuntu-latest
    name: Build/Push Docker
    steps:
    - name: Checkout current repo
      uses: actions/checkout@v2
      with:
        path: repo
    - name: Build
      run: |
        ls
        cd repo
        docker build --pull . -f Dockerfile.build -t betashil/rmd-render-site
    - name: Push
      run: |
        docker login --username "${{ secrets.DOCKER_HUB_USER }}" --password "${{ secrets.DOCKER_HUB_PASSWORD }}"
        docker push betashil/rmd-render-site
