on:
  push:
  schedule:
    - cron: '12 7 * * 1/3'

jobs: 
  build_docker:
    runs-on: ubuntu-latest
    name: Build and publish docker image
    steps:
    - name: Checkout current repo
      uses: actions/checkout@v2
    - run: build_docker.sh
    - name: Dockerize
      if: success()
      uses: manusa/actions-publish-docker@320f1d1e
      with:
        name: betashil/rmd-render-sit
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
